services:
    #Postgress Database
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
    #Express API server    
    api:
        build: ./
        image: docker.io/puja8788/simple_blog-api
        environment:
          - POSTGRES_USERNAME=postgres
          - POSTGRES_HOST=postgres
          - POSTGRES_DB=simple_blog_api
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_PORT=5432
          - PORT=3000
        ports:
            - '8085:3000'